version: '3.8'

services:
  db:
    volumes:
      - ${LOCAL_WORKSPACE_FOLDER}/myproject/docker/dkdata/postgres:/var/lib/postgresql/data
  web:
    volumes:
      - ${LOCAL_WORKSPACE_FOLDER}/myproject:/app
  nginx:
    volumes:
      - ${LOCAL_WORKSPACE_FOLDER}/myproject/docker/nginx/default_local:/etc/nginx/conf.d/default.conf
